/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma;

import domen.Radnik;
import sesija.Sesija;

/**
 *
 * @author Dusan
 */
public class FrmMain extends javax.swing.JFrame {

    Radnik ulogovaniRadnik;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        this.ulogovaniRadnik = Sesija.getInstanca().getRadnik();
        this.setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Glavna forma");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        lblUlogovaniRadnik = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        mbUnos = new javax.swing.JMenu();
        jmiUnosRacun = new javax.swing.JMenuItem();
        jmiUnosKlijent = new javax.swing.JMenuItem();
        jmiUnosAkcija = new javax.swing.JMenuItem();
        mbPretraga = new javax.swing.JMenu();
        jmiPreKlijent = new javax.swing.JMenuItem();
        jmiPreGorivo = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovaniRadnik.setText("jLabel1");

        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        mbUnos.setText("Unos");

        jmiUnosRacun.setText("Racun");
        jmiUnosRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosRacunActionPerformed(evt);
            }
        });
        mbUnos.add(jmiUnosRacun);

        jmiUnosKlijent.setText("Klijent");
        jmiUnosKlijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosKlijentActionPerformed(evt);
            }
        });
        mbUnos.add(jmiUnosKlijent);

        jmiUnosAkcija.setText("Akcija");
        jmiUnosAkcija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosAkcijaActionPerformed(evt);
            }
        });
        mbUnos.add(jmiUnosAkcija);

        jMenuBar2.add(mbUnos);

        mbPretraga.setText("Pretraga");

        jmiPreKlijent.setText("Klijent");
        jmiPreKlijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPreKlijentActionPerformed(evt);
            }
        });
        mbPretraga.add(jmiPreKlijent);

        jmiPreGorivo.setText("Gorivo");
        jmiPreGorivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPreGorivoActionPerformed(evt);
            }
        });
        mbPretraga.add(jmiPreGorivo);

        jMenuBar2.add(mbPretraga);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(449, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovaniRadnik)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblUlogovaniRadnik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUnosRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosRacunActionPerformed
        this.setVisible(false);
        new FrmRacun(this).setVisible(true);
    }//GEN-LAST:event_jmiUnosRacunActionPerformed

    private void jmiUnosKlijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosKlijentActionPerformed
        this.setVisible(false);
        new FrmKlijent(this).setVisible(true);
    }//GEN-LAST:event_jmiUnosKlijentActionPerformed

    private void jmiUnosAkcijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosAkcijaActionPerformed
        new FrmNovaAkcija(this, true).setVisible(true);
    }//GEN-LAST:event_jmiUnosAkcijaActionPerformed

    private void jmiPreKlijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPreKlijentActionPerformed
        this.setVisible(false);
        new FrmPretragaKlijenta(this).setVisible(true);
    }//GEN-LAST:event_jmiPreKlijentActionPerformed

    private void jmiPreGorivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPreGorivoActionPerformed
        this.setVisible(false);
        new FrmPretragaGoriva(this).setVisible(true);
    }//GEN-LAST:event_jmiPreGorivoActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        this.dispose();
        new FrmLogin().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jmiPreGorivo;
    private javax.swing.JMenuItem jmiPreKlijent;
    private javax.swing.JMenuItem jmiUnosAkcija;
    private javax.swing.JMenuItem jmiUnosKlijent;
    private javax.swing.JMenuItem jmiUnosRacun;
    private javax.swing.JLabel lblUlogovaniRadnik;
    private javax.swing.JMenu mbPretraga;
    private javax.swing.JMenu mbUnos;
    // End of variables declaration//GEN-END:variables

    public void setUlogovaniRadnik(Radnik ulogovaniRadnik) {
        this.ulogovaniRadnik = ulogovaniRadnik;
    }

}
